AWSTemplateFormatVersion : '2010-09-09'
Description: Zoom to Opencast video ingester

Parameters:

  CodeBucket:
    Type: String
  CloudwatchLogGroup:
    Type: String
  VpcSecurityGroupId:
    Type: String
  VpcSubnetId:
    Type: String
  OCCluster:
    Type: String
  OCAdminIp:
    Type: String
  OcApiUser:
    Type: String
  OcApiPass:
    Type: String

Resources:

  OCMetricsRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${AWS::StackName}-role"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
        - Action: sts:AssumeRole
          Effect: Allow
          Principal:
            Service: lambda.amazonaws.com
        - Action: sts:AssumeRole
          Effect: Allow
          Principal:
            Service: !Sub "logs.${AWS::Region}.amazonaws.com"
      ManagedPolicyArns:
      - "arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole"
      Policies:
      - PolicyName: !Sub "${AWS::StackName}-policy"
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
          - Effect: "Allow"
            Action:
            - "cloudwatch:*"
            - "logs:*"
            Resource: "*"

  OCMetricsFunction:
    Type: AWS::Lambda::Function
    Properties:
      Handler: function.handler
      Runtime: python3.6
      Timeout: 30
      Role: !GetAtt [OCMetricsRole, Arn]
      FunctionName: !Sub "${AWS::StackName}-function"
      Environment:
        Variables:
          OC_ADMIN_URL: !Ref OCAdminIp
          OC_API_USER: !Ref OcApiUser
          OC_API_PASS: !Ref OcApiPass
          OC_CLUSTER: !Ref OCCluster
          DEBUG: 0
      Code:
        S3Bucket: !Ref CodeBucket
        S3Key: !Sub "oc-workflow-metrics/${AWS::StackName}/function.zip"
      VpcConfig:
        SecurityGroupIds:
        - !Ref VpcSecurityGroupId
        SubnetIds:
        - !Ref VpcSubnetId

  OCMetricsLogSubscriptionFilter:
    Type: AWS::Logs::SubscriptionFilter
    DependsOn:
      - OCMetricsFunction
    Properties:
      LogGroupName: !Ref CloudwatchLogGroup
      DestinationArn: !GetAtt [OCMetricsFunction, Arn]
      FilterPattern: 'WORKFLOW-PERFORMANCE-METRIC'

  OCMetricsLogSubscriptionPermission:
    Type: AWS::Lambda::Permission
    DependsOn:
    - OCMetricsFunction
    Properties:
      FunctionName: !Ref OCMetricsFunction
      Action: lambda:InvokeFunction
      Principal: !Sub "logs.${AWS::Region}.amazonaws.com"

